ggplot(aes(x,y=price),data=diamonds) +geom_point()
names(diamonds)
cor.test(diamonds$price,diamonds$z,method='pearson')
ggplot(aes(x=price,y=depth),data=diamonds)
ggplot(aes(x=price,y=depth),data=diamonds) +geom_point(alpha=1/100)+scale_x_continuous(limits=c(0,500),breaks = seq(0,500,2))
cor.test(diamonds$price,diamonds$depth,method='pearson')
ggplot(aes(x=price,y=depth),data=diamonds)+xlim(0,(quantile(diamonds$price,0.99))+ylim(0,(quantile(diamonds$depth,0.99))+geom_point()
volume<-(diamonds$x*diamonds$y*diamonds$z)
ggplot(aes(x=price,y=volume),data=diamonds) +geom_point()
count(diamonds$volume==0)
install.packages('plyr')
cor.test(diamonds$price,(subset(diamonds, (x*y*z)<800 | (x*y*z)>0))),method='pearson')
volume2<-subset(diamonds, (x*y*z)<800 | (x*y*z)>0)
with(subset(diamonds,(volume>0) & (volume<=800)),cor.test(volume,price))
with(subset(diamonds, (volume > 0) & (volume <= 800)),cor.test(volume,price))
ggplot(aes(x=price,y=subset(diamonds, (volume > 0) & (volume <= 800)))),data=diamonds) +geom_point()
p1 <- ggplot(data = subset(diamonds, (volume > 0) & (volume <= 800)), aes(x = volume, y = price)) + geom_point()
p2<-p1+geom_smooth()
p3 <- p1 + stat_smooth(method = "lm", formula = y ~ x, size = 1) + coord_cartesian(ylim = c(0,20000))
p4 <- p1 + stat_smooth(method = "lm", formula = y ~ poly(x, 2), size = 1) + coord_cartesian(ylim = c(0,20000))
p5 <- p1 + stat_smooth(method = "lm", formula = y ~ poly(x, 3), size = 1) + coord_cartesian(ylim = c(0,20000))
library(gridExtra)
grid.arrange(p2,p3,p4,p5,ncol=2)
diamondsByClarity <- diamonds %>% group_by(clarity) %>% summarise(mean_price = mean(price), median_price = median(price), min_price = min(price), max_price = max(price), n= n())
diamondsByClarity
install.packages('gridExtra')
?grid.arrange
diamonds_by_clarity <- group_by(diamonds, clarity)
diamonds_mp_by_clarity <- summarise(diamonds_by_clarity, mean_price = mean(price))

diamonds_by_color <- group_by(diamonds, color)
diamonds_mp_by_color <- summarise(diamonds_by_color, mean_price = mean(price))
p1<-ggplot(diamonds_mp_by_color,aes(x=color,y=mean_price,fill=collor))+geom_bar(stat="identity")
p2 <- ggplot(diamonds_mp_by_color, aes(x = color, y = mean_price, fill= color)) + geom_bar(stat = "identity")
grid.arrange(p1,p2,ncol=2)
cal<-read.csv('99b1cd3854ac337c007b05ae44988529.csv')
pf<-read.csv('indicator hiv estimated prevalence% 15-49.csv')
ggplot(aes(x=2010,y=2011),data=pf) +geom_point()
Tenmean<-mean(2010, data=pf)
Elevenmean<-mean(2010, data=pf)
ggplot(aes(x=Tenmean,y=Elevenmean),data=pf) +geom_point()
cor.test(pf$x2010,pf$x2011,method='pearson')
names(pf)
cor.test(pf$ee,pf$ff,method='pearson')
?cor.test
