library(ggplot2)
pf<-read.csv('pseudo_facebook.tsv',sep='\t')
qplot(x=age,y=friend_count,data=pf)
qplot(age,friend_count,data=pf)
ggplot(aes(x=age,y=friend_count),data=pf)+geom_point()
summary(pf$age)
ggplot(aes(x=age,y=friend_count),data=pf)+geom_point() +xlim(13,90)
ggplot(aes(x=age,y=friend_count),data=pf)+geom_point(alpha=1/20) +xlim(13,90)
ggplot(aes(x=age,y=friend_count),data=pf)+geom_jitter(alpha=1/20) +xlim(13,90)
?coord_trans
ggplot(aes(x=age,y=friend_count),data=pf)+geom_jitter(alpha=1/20) +xlim(13,90)+coord_trans(y="sqrt")
data(women)
qplot(x = height, data = women) +  coord_trans(x = "log10")
ggplot(aes(x = age, y=friend_count), data = pf) +geom_point(alpha=1/20) +xlim(13,90)+  coord_trans(y = "sqrt")
ggplot(aes(x = age, y=friend_count), data = pf) +geom_point(alpha=1/20,position=position_jitter(h=0))+xlim(13,90)+  coord_trans(y = "sqrt")
names(pf)
ggplot(aes(x = age, y=friendships_initiated), data = pf) +geom_point(alpha=1/20,position=position_jitter(h=0))+xlim(13,90)+  coord_trans(y = "sqrt")
install.packages('dplyer')
library(dplyr)
age_groups<-group_by(pf,age)
install.packages("dplyr")
pf.fc_by_age<-summarise(age_groups,friend_count_mean=mean(friend_count),friend_count_median=median(friend_count),n=n())
head(pf.fc_by_age)
pf.fc_by_age<-pf %>% group_by(age) %>% sumarise(friend_count_mean = mean(friend_count),friend_count_median = median(as.numeric(friend_count)),n=n()) %>% arrange(age)
avgFC<-mean(friend_count, data=pf)
qplot(x=avgfc,y=age,data=pf)
qplot(pf %>% group_by(age) %>% sumarise(friend_count_mean = mean(friend_count),n=n())%>% arrange(age))
ggplot(aes(age,friend_count_mean),data=pf.fc_by_age)+geom_point()
ggplot(aes(age,friend_count_mean),data=pf.fc_by_age)+geom_line()
library(reshape2)
ggplot(aes(x=age,y=friend_count),data=pf) +xlim(13,90)+geom_point(alpha=0.05,position=position_jitter(h=0),color='orange')+coord_trans(y='sqrt')+geom_line(stat='summary',fun.y=mean)+geom_line(state='summary',fun.y=quantile,probs=0.1,linetype=2,color='blue')+geom_line(stat='summary',fun.y=quantile,probs=0.5,color='blue')+geom_line(stat='summary',fun.y=quantile,probs=0.9,linetype=2,color='blue')
?quantile
?coord_cartesian()
ggplot(aes(x=age,y=friend_count),data=pf) +coord_cartesian(xlim=c(13,70),ylim=c(0,1000))+geom_point(alpha=0.05,position=position_jitter(h=0),color='orange')+geom_line(stat='summary',fun.y=mean)+geom_line(state='summary',fun.y=quantile,probs=0.1,linetype=2,color='blue')+geom_line(stat='summary',fun.y=quantile,probs=0.5,color='blue')+geom_line(stat='summary',fun.y=quantile,probs=0.9,linetype=2,color='blue')
?cor.test
cor.test(pf$age,pf$friend_count,method='pearson')
with(pf,cor.test(age,friend_count,method='pearson'))
with(subset(pf,age<=70),cor.test(age,friend_count,method='pearson'))
with(subset(pf,age<=70),cor.test(age,friend_count))
with(subset(pf,age<=70),cor.test(age,friend_count,method='spearman'))
names(pf)
ggplot(aes(x=www_likes_received,y=likes_received),data=pf)+geom_point()+xlim(0,(quantile(pf$www_likes_received,0.95)))+ylim(0,(quantile(pf$likes_received,0.95)))+geom_smooth(method='lm',color='red')
cor.test(pf$www_likes_received,pf$likes_received,method='pearson')
install.packages('alr3')
library(alr3)
data("Mitchell")
?Mitchell
names(Mitchell)
ggplot(aes(x=Month,y=Temp),data=Mitchell)+coord_cartesian(xlim=c(0,500),ylim=c(0,30))+geom_point()+scale_x_discrete(breaks=seq(0,203,12))
cor.test(Mitchell$Month,Mitchell$Temp,method='pearson')
pf$age_with_months<-pf$age+(12-pf$dob_month)/12
pf.fc_by_age_months<-pf%>% group_by(age_with_months)%>%summarise(friend_count_mean = mean(friend_count),friend_count_median=median(friend_count),n=n())%>% arrange(age_with_months)
age_with_months_groups<-group_by(pf,age_with_months)
data("pf")
friend_count_mean<-mean(friend_count, data=pf)
ggplot(aes(x=friend_count_mean,y=age_with_months),data=(subset(pf,age<71))) +geom_point()
friend_count_mean<-mean(pf$friend_count)       