setwd("C:\Users\Peter Fontana\Documents\R\R-3.2.2\RProjects")
?functionName
pf<-read.csv('pseudo_facebook.tsv', sep = '\t')
qplot(x = dob_day, data = pf)
ggplot(aes(x = dob_day), data = pf) + 
  +     geom_histogram() + 
  +     scale_x_discrete(breaks = 1:31)
qplot(x = dob_day, data = pf)
names(pf)
pf<-read.csv('pseudo_facebook.tsv', sep = '\t')
qplot(x = dob_day, data = pf)
names(pf)
qplot(x = dob_day, data = pf) +
  + scale_x_discrete(breaks=1:31)
qplot(x = dob_day, data = pf) +
  +     + scale_x_discrete(breaks=1:31) +
  + facet_wrap(~dob_month, ncol = 3)
qplot(x = dob_day, data = pf) + scale_x_discrete(breaks=1:31) + facet_wrap(~dob_month, ncol = 3)
qplot(x = friend_count, data = pf)
qplot(x = friend_count, data = pf, xlim = c(0,1000))
qplot(x=friend_count, data=pf,binwidth = 25) +scale_x_continuous(limits=c(0,1000),breaks = seq(0,1000,50))
qplot(x=friend_count, data=pf,binwidth = 25) +scale_x_continuous(limits=c(0,1000),breaks = seq(0,1000,50))+facet_wrap(~gender,ncol = 2)
qplot(x=friend_count, data=subset(pf,!is.na(gender)),binwidth = 25) +scale_x_continuous(limits=c(0,1000),breaks = seq(0,1000,50))+facet_wrap(~gender,ncol = 2)
table(pf$gender)
by(pf$friend_count,pf$gender,summary)
qplot(x=tenure, data=pf, color=I('black'),fill=I('#099009'))
qplot(x=tenure, data=pf, binwidth=30, color=I('black'),fill=I('#099009'))
ggplot(aes(x = tenure/365), data = pf) + geom_histogram(binwidth = .25, color = 'black', fill = '#F79420')
ggplot(aes(x = tenure / 365), data = pf) + geom_histogram(color = 'black', fill = '#F79420') + scale_x_continuous(breaks = seq(1, 7, 1), limits = c(0, 7)) + xlab('Number of years using Facebook') + ylab('Number of users in sample')
qplot((x = age), data = pf, binwidth=30) + geom_histogram(color = 'black', fill = '#F79420') + scale_x_continuous(breaks = seq(1, 7, 1), limits = c(0, 7))
ggplot(aes(x = age), data = pf) + geom_histogram(binwidth = 1, fill = '#5760AB') + scale_x_discrete(breaks = seq(0, 113, 5))
summary(pf$age)
qplot(x=friend_count,data=pf)
summary(pf$friend_count)
summary(log10(pf$friend_count))
summary(log10(pf$friend_count)+1)
summary(sqrt(pf$friend_count))
install.packages("gridExtra")
p1=ggplot(friend_count,data=pf)
p1<-qplot(x=friend_count,data=pf)
p2<-qplot(x=log10(friend_count)+1,data=pf)
p3<-qplot(x=sqrt(friend_count),data=pf)
grid.arrange(p1,p2,p3,ncol=2)
p1<-ggplot(aes(x=friend_count),data=pf)+geom_histogram()
p2<-p1+scale_x_log10()
p3<-p1+scale_x_sqrt()
grid.arrange(p1,p2,p3,ncol=1)
qplot(x=friend_count,data=subset(pf,!is.na(gender)),binwidth=10,geom='freqpoly',color=gender)+scale_x_continuous(lim=c(0,1000),breaks=seq(0,1000,50))
qplot(x=friend_count,y=..count../sum(..count..),data=subset(pf,!is.na(gender)),xlab='Friend Count',ylab='Proportion of Users with that friend count',binwidth=10,geom='freqpoly',color=gender)+scale_x_continuous(lim=c(0,1000),breaks=seq(0,1000,50))
qplot(x=www_likes,y=..count../sum(..count..),data=subset(pf,!is.na(gender)),geom='freqpoly',color=gender)+scale_x_log10()
by(pf$www_likes,pf$gender,sum)
qplot(x=gender,y=friend_count,data=subset(pf,!is.na(gender)),geom='boxplot',ylim=c(0,1000))
by(pf$friendships_initiated,pf$gender,summary)
by(pf$friendships_initiated,pf$gender,sum)
qplot(x=gender,y=friendships_initiated,data=subset(pf,!is.na(gender)),geom='boxplot')+coord_cartesian(ylim=c(0,150))
mobile_check_in<-NA
pf$mobile_check_in<-ifelse(pf$mobile_likes>0,1,0)
pf$mobile_check_in<-factor(pf$mobile_check_in)
summary(pf$mobile_check_in)
sum(pf$mobile_check_in==1)/length(pf$mobile_check_in)
data(diamonds)
summary(diamonds)
by(diamonds)
install.packages("Hmisc")
library(Hmisc)
names(diamonds)
fdata<-factor(diamonds)
diamonds$color
?diamonds
ggplot(aes(x = price), data = diamonds) + geom_histogram()
summary(diamonds$price)
summary(diamonds$price<500)
summary(diamonds$price>15000)
ggplot(aes(x = price), data = diamonds) + geom_histogram(binwidth=30)+scale_x_continuous(limits=c(0,1000),breaks = seq(0,1000,50))
ggsave()
summary(diamonds$cut)
summary(diamonds$price)
qplot(x=price,data=diamonds)+facet_wrap(~cut)
min(diamonds$cut=="Fair")
min(diamonds$cut=="Good")
by(diamonds$price,diamonds$cut,summary)
by(diamonds$price, diamonds$cut,max)
by(diamonds$price, diamonds$cut,min)
by(diamonds$price, diamonds$cut,median)
qplot(x=price,data=diamonds)+facet_wrap(~cut, scales="free_y")
qplot(x=price/carat,data=diamonds)+facet_wrap(~cut)
qplot(x=price/carat,data=diamonds, binwidth=10)+facet_wrap(~cut)+scale_x_log10()
qplot(x=price,y=cut,data=diamonds)),geom='boxplot')
qplot(x=price,y=cut,data=diamonds),geom='boxplot')
qplot(x=price,y = carat,data = diamonds,geom = "boxplot")
by(diamonds$price,diamonds$color=="D")
by(diamonds$price/diamonds$carat,diamonds$color, summary)
by(diamonds$price,diamonds$color,IQR)
diamonds %>% group_by(color) %>% filter(color == "D") %>% summarise(Quartile.25 = quantile(price, 0.25), Quartile.75 = quantile(price, 0.75), IQR = Quartile.75 - Quartile.25)
qplot(x=price/carat,y = color,data = diamonds,geom = "boxplot")
qplot(x=carat,data=diamonds,binwidth=10,geom='freqpoly')
ggsave(/www.gapminder.org/data/)
library(ggplot2)
pf<-read.csv('indicator hiv estimated prevalence% 15-49.csv')
names(pf)
qplot(x=2011,data=pf) + geom_histogram()
ggplot(aes(x = 2011), data = pf) + geom_histogram
qplot(x=2011,data=pf) + geom="boxplot"
qplot(x=2011,y="Estimated.HIV.Prevalence.....Ages.15.49.",data = pf,geom = "boxplot")
qplot(x=2011,data=pf,binwidth=10,geom='freqpoly')
cal<-read.csv('99b1cd3854ac337c007b05ae44988529.csv')
names(cal)
qplot(x=strptime(Start,format="%m",tz=""),data=cal) + geom_histogram()
