ggplot(aes(x=price,y=x),data=diamonds)+geom_point(aes(color=cut))+facet_wrap(~color)
names(diamonds)
ggplot(aes(x=price,y=table),data=diamonds)+geom_point(aes(color=cut))+facet_wrap(~color)
ggplot(aes(x=(x*y*z),y=price),data=subset(quantile(diamonds, 0.99))+geom_point(aes(color=clarity))+scale_x_log10(price)
pf<-read.csv('pseudo_facebook.tsv', sep = '\t')
names(pf)
prop_initiated<-(pf$friend_count-pf$friendships_initiated)
fb <- fb %>% mutate(prop_initiated = ifelse(friend_count > 0, friendships_initiated/friend_count, 0))
mutate(year_joined = floor(2014 - tenure/365), year_joined_bucket = cut(year_joined, breaks=c(2004, 2009, 2011, 2012, 2014))) 
install.packages("dplyr")
fb2 <- fb %>% mutate(prop_initiated = ifelse(friend_count > 0, friendships_initiated/friend_count, 0))
ggplot(subset(fb2, tenure > 0), aes(x=tenure, y=prop_initiated)) +geom_line(aes(color=year_joined_bucket), stat='summary', fun.y=mean) +theme_minimal()
ggplot(subset(fb, tenure > 0), aes(x=tenure, y=prop_initiated)) + #geom_line(aes(color=year_joined_bucket), stat='summary', fun.y=mean) + geom_smooth(aes(color = year_joined_bucket))
)
fb %>% filter(year_joined_bucket == "(2012,2014]") %>% summarise(avg = mean(prop_initiated, na.rm=TRUE))
ggplot(diamonds, aes(x = cut, y = price/carat, color = color)) +  geom_jitter() +  facet_wrap(~clarity) +  scale_color_brewer(type = 'div')
prof_scores <- c(0, 358, 420, 482, 545, 607, 669, 1000)
country_gender <- country_data %>%  group_by(Country, Gender) %>%  summarise(avg_math = mean(Math), avg_reading = mean(Reading), avg_science = mean(Science), n = n() ) %>%  arrange(avg_math, avg_reading, avg_science)