library(ggplot2)
pf<-read.csv('pseudo_facebook.tsv',sep='\t')
ggplot(aes(x=gender,y=age),data=subset(pf,!is.na(gender)))+geom_boxplot()+stat_summary(fun.y=mean,geom='point',shape=4)
ggplot(aes(x=age,y=friend_count),data=subset(pf,!is.na(gender)))+geom_line(aes(color=gender),stat='summary',fun.y=median)
install.packages("dplyr")
install.packages('alr3')


new_groupings<-group_by(pf,age,gender)
library(dplyr)
library(alr3)
pf.fc_by_age_gender<-pf %>% filter(!is.na(gender)) %>% group_by(age,gender) %>% sumarise(friend_count_mean = mean(friend_count),friend_count_median = median(friend_count),n=n()) %>% ungroup() %>% arrange(age)
ggplot(aes(x=age,y=median_friend_count),data=pf.fc_by_age_gender)+geom_line(aes(color=gender))
install.packages("reshape2")
library(reshape2)
pf.fc_by_age_gender.wide <-subset(pf.fc_by_age_gender[c('age', 'gender', 'median_friend_count')], !is.na(gender)) %>% spread(gender, median_friend_count) %>% mutate(ratio = male / female)
ggplot(aes(x=age,y=female/male), data=pf.fc_by_age_gender.wide)+geom_line() + geom_hline(yintercept=1,alpha=0.3,linetype=2)
install.packages('ggplot')
pf$year_joined<-floor(2014-pf$tenure/365)
summary(pf$year_joined)
table(pf$year_joined)
?cut
pf$year_joined.bucket<-cut(pf$year_joined,c(2004,2009,2011,2012,2014))
table(pf$year_joined.bucket,useNA='ifany')
ggplot(aes(x=age,y=friend_count,data=subset(pf,!is.na(gender))))+geom_line(aes(color=gender),stat='summary',fun.y=median)
ggplot(aes(x=age,y=friend_count,data=subset(pf,!is.na(yeah_joined.bucket))))+geom_line(aes(color=year_joined.bucket),stat='summary',fun.y=median)

with(subset(pf,tenure>=1),summary(friend_count/tenure))
ggplot(aes(x=age,y=friendships_initiated/tenure,data=subset(pf,tenure>=1)+geom_line(aes(color=year_joined.bucket))
ggplot(aes(x=tenure,y=friendships_initiated/tenure,data=subset(pf,tenure>=1)+geom_line(aes(color=year_joined.bucket),stat='summary',fun.y=mean)
ggplot(aes(x = 7 * round(tenure / 7), y = friendships_initiated / tenure),data = subset(pf, tenure > 0)) +geom_line(aes(color = year_joined.bucket),stat = "summary",fun.y = mean)
ggplot(aes(x = 7 * round(tenure / 7), y = friendships_initiated / tenure),data = subset(pf, tenure > 0)) +geom_smooth(aes(color = year_joined.bucket)
yo<-read.csv('yogurt.csv')
str(yo)
yo$id<-factor(yo$id)
head(yo)
qplot(data=yo,x=price,fill=I('#F79420'))
install.packages("ggplot2")
library(ggplot2)
summary(yo)
?transform
yo<-transform(yo,all.purchases=strawberry+blueberry+pina.colada+plain+mixed.berry)
summary(yo$all.purchases)
ggplot(aes(x=time,y=price),data=yo)+geom_jitter(alpha=1/4,shape=21,fill=I('#F79420'))
?set.seed
set.seed(4230)
sample.ids<-sample(levels(yo$id),16)
ggplot(aes(x=time,y=price),data=subset(yo,id%in% sample.ids))+facet_wrap(~id)+geom_line()+geom_point(aes(size=all.purchases),pch=1)
sample.ids
set.seed(3230)
ggplot(aes(x=time,y=price),data=subset(yo,id%in% sample.ids))+facet_wrap(~id)+geom_line()+geom_point(aes(size=all.purchases),pch=1)
#install.packages(GGally)
library(GGally)
install.packages(ggplot)
install.packages("ggplot2")
set.seed(1836)
pf_subset<-pf[,c(2:15))]
names(pf_subset)
ggpairs(pf_subset[sample.int(nrow(pf_subset),1000),])
nci<-read.table('nci.tsv')
colnames(nci)<-c(1:64)
library(reshape2)
nci.long.samp<-melt(as.matrix(nci[1:200,]))
names(nci.long.samp)<-c('gene','case','value')
head(nci.long.samp)
ggplot(aes(y=gene,x=case,fill=value),data=nci.long.samp)+geom_tile()+scale_fill_gradientn(colours = colorRampPalette(c('blue','red'))(100))
